### ISSUE TITLE
High memory usage in some cases

### ISSUE THREAD

**Issue by abhay-agarwal** [mesosphere/hdfs#116]
In some cases, a namenode may overflow its memory allocation despite being allocated as much as 2 gigabytes. This is definitely undesirable behavior and either implies a memory leak or some misconfiguration of heap parameters.

**Comment by elingg** [comment]
Thanks @abhay-agarwal. Are you certain this is not related to HDFS itself having different memory requirements on different environments? We are calling the native HDFS commands in our executor, it would be interesting to test running the native HDFS commands manually and seeing their memory usage. It would be great if you could investigate further why this is happening.

**Comment by elingg** [comment]
Actually after discussion with @brndnmtthws, we need to give nodes higher memory settings for HDFS nodes in general. So I think this issue is safe to close. His comment is here:

the default memory settings for HDFS are much too small

brenden [6:36 PM]
they should be at least 1g for the heap

brenden [6:36 PM]
with a 25% overhead

brenden [6:36 PM]
so 1250m allocated per datanode

brenden [6:36 PM]
NNs should have at least 4g

brenden [6:36 PM]
with 25% overhead

brenden [6:36 PM]
JNs can match DNs

brenden [6:36 PM]
for a big cluster, it should be much more

brenden [6:37 PM]
16gb for NN, 4gb for JN & DN

**Comment by brndnmtthws** [comment]
See https://mesosphere.atlassian.net/browse/DCOS-919

We must err on the side of safety, _especially_ with HDFS.
