### ISSUE TITLE
Mesos-site.xml variable substitution

### ISSUE THREAD

**Issue by ddispaltro** [mesosphere/hdfs#133]
I think there is a problem with the move from `0.1.1` to `master` branch in how you manage the environment variables.  My understanding is that when you execute ./bin/hdfs-mesos it uses `envsubst` to replace the variables in `mesos-site.xml`from /tmp/mesos-site.xml to `$framework_dir/etc/hadoop/mesos-site.xml` but then when everything get's launched the updated mesos-site.xml isn't distributed with the package.  

So you run into issues like this:

![screen shot 2015-06-06 at 2 15 31 pm](https://cloud.githubusercontent.com/assets/46037/8021493/8e89996e-0c56-11e5-8edb-bc59d4d6bcd4.png)

With out full knowing how this all works, I would assume either the launcher needs to create a tgz with all the materialized settings or something special like what you do with the hdfs-site.xml; which looks like it gets distributed differently.

**Comment by elingg** [comment]
hello @nicgrayson, any comment on this? It seems the latest PR doesn't resolve the env variables properly since envsubst is being done by the scheduler, but not the packaged executors. Please let me know if you have thoughts on how to proceed. I can also revert the last PR if it is not working.

**Comment by nicgrayson** [comment]
@elingg this requires a bigger rewrite of the executor code. Right not there is no way to use any non defaulted values in the executor since it reads from the prebuilt tarball. There are 2 ways of fixing this:

1. The calls to schedulerConf need to change to read from the distributed hdfs-site.xml instead
2. The mesos-site.xml needs to also be distributed

I don't have time to do this currently but I think this should be a good enough outline for someone else to do it.

**Comment by ddispaltro** [comment]
Basically as a hack I made the hdfs-mesos command do the following:

https://gist.github.com/ddispaltro/0625fe8e4aeab61a522b

which more or less does the environment substitution then recompresses the tgz before distribution to the slaves.

**Comment by elingg** [comment]
After reverting the latest PR, this issue should be resolved. @nicgrayson is making a few fixes before merging that change in again. Feel free to reopen if this issue crops up again.
